plugins {
	id 'net.fabricmc.fabric-loom' version "${loom_version}"
	id 'org.jetbrains.kotlin.jvm' version '2.4.20'
	id 'maven-publish'
}

version = project.mod_version
group = project.maven_group

base {
	archivesName = project.archives_base_name
}

repositories {
	maven {
		name = 'HuaweiMavenMirror'
		url = 'https://mirrors.huaweicloud.com/repository/maven'
	}
	mavenCentral()

	maven {
		name "enjaraiMavenReleases"
		url "https://maven.enjarai.dev/releases"
	}

}

loom {
    splitEnvironmentSourceSets()

	mods {
		"creeperhealing_sylvan" {
			sourceSet sourceSets.main
			sourceSet sourceSets.client
		}
	}
    runs {
		// This adds a new gradle task that runs the datagen API: "gradlew runDatagen"
		datagen {
			inherit server
			name "Data Generation"
			vmArg "-Dfabric-api.datagen"
			vmArg "-Dfabric-api.datagen.output-dir=${file("src/main/generated")}"
			vmArg "-Dfabric-api.datagen.modid=creeperhealing_sylvan"
 
			runDir "build/datagen"
		}
	}
}

// Add the generated resources to the main source set
sourceSets {
	main {
		resources {
			srcDirs += [
					'src/main/generated'
			]
		}
	}
}
dependencies {
	// To change the versions see the gradle.properties file
	minecraft "com.mojang:minecraft:${project.minecraft_version}"
	implementation "net.fabricmc:fabric-loader:${project.loader_version}"

	implementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"

	// Monkey Config
	include(implementation("io.github.arkosammy12:monkey-config:${project.monkey_config}"))

	// Fabric Permissions API
	include(implementation('me.lucko:fabric-permissions-api:0.7.0'))

	implementation("net.fabricmc:fabric-language-kotlin:${property("fabric_kotlin_version")}")
	testImplementation 'org.junit.jupiter:junit-jupiter:5.11.4'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'

}

test {
	useJUnitPlatform()
}

processResources {
	inputs.property "version", project.version

	filesMatching("fabric.mod.json") {
		expand "version": project.version
	}
}

tasks.withType(JavaCompile).configureEach {
	it.options.release = 25
}

kotlin {
	compilerOptions {
		jvmTarget = org.jetbrains.kotlin.gradle.dsl.JvmTarget.JVM_25
	}
}

java {
	// Loom will automatically attach sourcesJar to a RemapSourcesJar task and to the "build" task
	// if it is present.
	// If you remove this line, sources will not be generated.
	withSourcesJar()

	sourceCompatibility = JavaVersion.VERSION_25
	targetCompatibility = JavaVersion.VERSION_25
}

jar {
	from("LICENSE") {
		rename { "${it}_${project.base.archivesName.get()}"}
	}
	from("COPYING.GPLv3")
	from("MONKEY-UTILS-LICENSE")
}

// configure the maven publication
publishing {
	publications {
		mavenJava(MavenPublication) {
			from components.java
		}
	}

	// See https://docs.gradle.org/current/userguide/publishing_maven.html for information on how to set up publishing.
	repositories {
		// Add repositories to publish to here.
		// Notice: This block does NOT have the same function as the block in the top level.
		// The repositories here will be used for publishing your artifact, not for
		// retrieving dependencies.
	}
}
